version: "3"
services:
  mysql:
    image: mysql
    env_file: ./mysql/.env
    environment:
      - TZ=Asia/Tokyo
    volumes: 
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d/
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

  node:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app
    env_file: ./.env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./app:/app
    tty: true
    working_dir: /app
    ports:
        - "3000:3000"
    depends_on:
      - mysql

volumes:
  db-data:
