version: "3"
services:
  mysql:
    image: mysql
    env_file: ./mysql/.env
    environment:
      - TZ=Asia/Tokyo
    volumes: 
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d/
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - backend

  node:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: node-mysql-app
    env_file: ./.env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./src:/app
    tty: true
    working_dir: /app
    ports:
        - "3000:3000"
    networks: 
      - backend
    depends_on:
      - mysql

networks:
  backend:
volumes:
  db-data:
